### ISSUE TITLE
infra: implement Continuous Integration

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/cicd#23]
# New Features

- Implements Continuous Integration via GitHub action
- Uses docker-compose to build, run, and test application

# Todos

- [x] Add workflow file with basic checkout
~- [x] Set up docker compose~
- [x] Build and run docker compose
- [ ] Run tests
- [x] Stop docker compose (necessary?)
